Repository marvelai-org/marvel-platform, pull requests merged in 2025-03, with the labels that each got.

#255 Feature/enhance mcq
  .github/workflows/develop-ci-cd.yml
  components/PrimaryTextAreaInput/PrimaryTextAreaInput.jsx
  components/PrimaryTextAreaInput/index.js
  components/PrimaryTextAreaInput/styles.js
  functions/controllers/marvelAIController.js
  functions/seed_data.json
  layouts/MainAppLayout/NavBar/Navbar.jsx
  layouts/MainAppLayout/NavMenu/NavMenu.jsx
  tools/components/ToolOutputHistoryDrawer/toolRenderers/QuizOutput.jsx
  tools/components/ToolRequestForm/ToolRequestForm.jsx
  tools/outputs/QuizResponse/QuizResponse.jsx
Labels: type:enhancement

#257 Update Name Styling Issue
  components/UserAvatar/styles.js
Labels: type:bug, type:refactoring

#259 Remove CI/CD deployment errors (DEV)
  next.config.js
Labels: type:bug, type:refactoring

#260 Disable onboarding flow after signin/up from platform
  functions/cloud_db_seed.js
  functions/controllers/userController.js
  libs/hooks/useRedirect.jsx
  templates/SignIn/SignInForm/SignInForm.jsx
Labels: type:bug, type:enhancement
